export const GET_MY_TASK_DETAIL = 'GET_MY_TASK_DETAIL';
export const SET_MY_TASK_DETAIL = 'SET_MY_TASK_DETAIL';

export const GET_MY_MEMBER = 'GET_MY_MEMBER';
export const SET_MY_MEMBER = 'SET_MY_MEMBER';
