export const GET_TASK_LIST_DATA_MANAGER = 'GET_TASK_LIST_DATA_MANAGER';
export const SET_TASK_LIST_DATA_MANAGER = 'SET_TASK_LIST_DATA_MANAGER';
export const CREATE_TASK_MANAGER = 'CREATE_TASK_MANAGER';