export const GET_TASK_LIST_DATA = 'GET_TASK_LIST_DATA';
export const SET_TASK_LIST_DATA = 'SET_TASK_LIST_DATA';
export const GET_TASK_DETAIL_DATA = 'GET_TASK_DETAIL_DATA';
export const SET_TASK_DETAIL_DATA = 'SET_TASK_DETAIL_DATA';
export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK'